Kan-23/signup
anmol02singh/OOCAA-UI pull request #2
Opened 2024-11-09 16:46 UTC by tahas022

I created a sign up page, and ensured it was responsive

2024-11-09 23:50 UTC, anmol02singh approved these changes

2024-11-10 18:48 UTC, tahas022 commented
There's an issue with the routing for now, because the signup page is not on it's own, App.js thinks its a part of the overall project and gives it the navbar as well. I'm going to fix this when we isolate the signup page and login page from the rest of the program. Just going to leave it for now so we can get the pages going. If someone has a better idea to solve it I'll give it a shot

2024-11-15 20:59 UTC, anmol02singh requested changes
looks sick but i see the routing buttons at the bottom of the page
![Screenshot 2024-11-15 154423](https://github.com/user-attachments/assets/6771925a-5fe3-4c99-8e88-92fad6283544)

2024-11-22 19:56 UTC, anmol02singh approved these changes
works on my end, those buttons are gone, looks great

2024-11-22 19:56 UTC, merged